export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const SITE_SIDEBAR = 'SITE_SIDEBAR';

// export const USER_LIST_START = 'USER_LIST_START';
// export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
// export const USER_LIST_FAIL = 'USER_LIST_FAIL';
// export const USER_LIST_FILTER = 'USER_LIST_FILTER';
// export const USER_DETAIL = 'USER_DETAIL';
// export const USER_DELETE = 'USER_DELETE';
// export const USER_ROLE_LIST = 'USER_ROLE_LIST';
// export const USER_PLAN_LIST = 'USER_PLAN_LIST';
// export const USER_ADD_EDIT_START = 'USER_ADD_EDIT_START';
// export const USER_ADD_EDIT_SUCCESS = 'USER_ADD_EDIT_SUCCESS';
// export const USER_ADD_EDIT_FAIL = 'USER_ADD_EDIT_FAIL';

export const FAQ_LIST_START = 'FAQ_LIST_START';
export const FAQ_LIST_SUCCESS = 'FAQ_LIST_SUCCESS';
export const FAQ_LIST_FAIL = 'FAQ_LIST_FAIL';
export const FAQ_DELETE = 'FAQ_DELETE';
export const FAQ_DETAIL = 'FAQ_DETAIL';
export const FAQ_ADD_EDIT_START = 'FAQ_ADD_EDIT_START';
export const FAQ_ADD_EDIT_SUCCESS = 'FAQ_ADD_EDIT_SUCCESS';
export const FAQ_ADD_EDIT_FAIL = 'FAQ_ADD_EDIT_FAIL';

export const EVENT_LIST_START = 'EVENT_LIST_START';
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL';
export const EVENT_LIST_FILTER = 'EVENT_LIST_FILTER';
export const EVENT_DETAIL = 'EVENT_DETAIL';
export const EVENT_ADD_EDIT_START = 'EVENT_ADD_EDIT_START';
export const EVENT_ADD_EDIT_SUCCESS = 'EVENT_ADD_EDIT_SUCCESS';
export const EVENT_ADD_EDIT_FAIL = 'EVENT_ADD_EDIT_FAIL';
export const EVENT_DELETE = 'EVENT_DELETE';
export const EVENT_COUNTRY_LIST = 'EVENT_COUNTRY_LIST';
export const EVENT_STATE_LIST = 'EVENT_STATE_LIST';
export const EVENT_USER_LIST_START = 'EVENT_USER_LIST_START';
export const EVENT_USER_LIST_SUCCESS = 'EVENT_USER_LIST_SUCCESS';
export const EVENT_USER_LIST_FAIL = 'EVENT_USER_LIST_FAIL';

export const MATERIAL_LIST_START = 'MATERIAL_LIST_START';
export const MATERIAL_LIST_SUCCESS = 'MATERIAL_LIST_SUCCESS';
export const MATERIAL_LIST_FAIL = 'MATERIAL_LIST_FAIL';
export const MATERIAL_LIST_FILTER = 'MATERIAL_LIST_FILTER';
export const MATERIAL_DETAIL = 'MATERIAL_DETAIL';
export const MATERIAL_ADD_EDIT_START = 'MATERIAL_ADD_EDIT_START';
export const MATERIAL_ADD_EDIT_SUCCESS = 'MATERIAL_ADD_EDIT_SUCCESS';
export const MATERIAL_ADD_EDIT_FAIL = 'MATERIAL_ADD_EDIT_FAIL';
export const MATERIAL_DELETE = 'MATERIAL_DELETE';
export const MATERIAL_COUNTRY_LIST = 'MATERIAL_COUNTRY_LIST';
export const MATERIAL_STATE_LIST = 'MATERIAL_STATE_LIST';
export const MATERIAL_USER_LIST_START = 'MATERIAL_USER_LIST_START';
export const MATERIAL_USER_LIST_SUCCESS = 'MATERIAL_USER_LIST_SUCCESS';
export const MATERIAL_USER_LIST_FAIL = 'MATERIAL_USER_LIST_FAIL';

export const ROLE_LIST_START = 'ROLE_LIST_START';
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS';
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL';
export const ROLE_LIST_FILTER = 'ROLE_LIST_FILTER';
export const ROLE_DETAIL = 'ROLE_DETAIL';
export const ROLE_ADD_EDIT_START = 'ROLE_ADD_EDIT_START';
export const ROLE_ADD_EDIT_SUCCESS = 'ROLE_ADD_EDIT_SUCCESS';
export const ROLE_ADD_EDIT_FAIL = 'ROLE_ADD_EDIT_FAIL';
export const ROLE_DELETE = 'ROLE_DELETE';
export const ROLE_COUNTRY_LIST = 'ROLE_COUNTRY_LIST';
export const ROLE_STATE_LIST = 'ROLE_STATE_LIST';
export const ROLE_USER_LIST_START = 'ROLE_USER_LIST_START';
export const ROLE_USER_LIST_SUCCESS = 'ROLE_USER_LIST_SUCCESS';
export const ROLE_USER_LIST_FAIL = 'ROLEL_USER_LIST_FAIL';

export const FUND_LIST_START = 'FUND_LIST_START';
export const FUND_LIST_SUCCESS = 'FUND_LIST_SUCCESS';
export const FUND_LIST_FAIL = 'FUND_LIST_FAIL';
export const FUND_LIST_FILTER = 'FUND_LIST_FILTER';
export const FUND_DETAIL = 'FUND_DETAIL';
export const FUND_ADD_EDIT_START = 'FUND_ADD_EDIT_START';
export const FUND_ADD_EDIT_SUCCESS = 'FUND_ADD_EDIT_SUCCESS';
export const FUND_ADD_EDIT_FAIL = 'FUND_ADD_EDIT_FAIL';
export const FUND_DELETE = 'FUND_DELETE';
export const FUND_CATEGORY_LIST = 'FUND_CATEGORY_LIST';

export const CATEGORY_LIST_START = 'CATEGORY_LIST_START';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';
export const CATEGORY_LIST_FILTER = 'CATEGORY_LIST_FILTER';
export const CATEGORY_DETAIL = 'CATEGORY_DETAIL';
export const CATEGORY_ADD_EDIT_START = 'CATEGORY_ADD_EDIT_START';
export const CATEGORY_ADD_EDIT_SUCCESS = 'CATEGORY_ADD_EDIT_SUCCESS';
export const CATEGORY_ADD_EDIT_FAIL = 'CATEGORY_ADD_EDIT_FAIL';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';
export const CATEGORY_CATEGORY_LIST = 'CATEGORY_CATEGORY_LIST';

export const USER_LIST_START = 'USER_LIST_START';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_FILTER = 'USER_LIST_FILTER';
export const USER_DETAIL = 'USER_DETAIL';
export const USER_ADD_EDIT_START = 'USER_ADD_EDIT_START';
export const USER_ADD_EDIT_SUCCESS = 'USER_ADD_EDIT_SUCCESS';
export const USER_ADD_EDIT_FAIL = 'USER_ADD_EDIT_FAIL';
export const USER_DELETE = 'USER_DELETE';
export const USER_LIST = 'USER_LIST';

export const CONTRIBUTOR_META_LIST_START = 'CONTRIBUTOR_META_LIST_START';
export const CONTRIBUTOR_META_LIST_SUCCESS = 'CONTRIBUTOR_META_LIST_SUCCESS';
export const CONTRIBUTOR_META_LIST_FAIL = 'CONTRIBUTOR_META_LIST_FAIL';
export const CONTRIBUTOR_META_LIST_FILTER = 'CONTRIBUTOR_META_LIST_FILTER';
export const CONTRIBUTOR_META_DETAIL = 'CONTRIBUTOR_META_DETAIL';
export const CONTRIBUTOR_META_ADD_EDIT_START = 'CONTRIBUTOR_META_ADD_EDIT_START';
export const CONTRIBUTOR_META_ADD_EDIT_SUCCESS = 'CONTRIBUTOR_META_ADD_EDIT_SUCCESS';
export const CONTRIBUTOR_META_ADD_EDIT_FAIL = 'CONTRIBUTOR_META_ADD_EDIT_FAIL';
export const CONTRIBUTOR_META_DELETE = 'CONTRIBUTOR_META_DELETE';

export const DIGITAL_LIBRARY_LIST_START = 'DIGITAL_LIBRARY_LIST_START';
export const DIGITAL_LIBRARY_LIST_SUCCESS = 'DIGITAL_LIBRARY_LIST_SUCCESS';
export const DIGITAL_LIBRARY_LIST_FAIL = 'DIGITAL_LIBRARY_LIST_FAIL';
export const DIGITAL_LIBRARY_LIST_FILTER = 'DIGITAL_LIBRARY_LIST_FILTER';
export const DIGITAL_LIBRARY_DETAIL = 'DIGITAL_LIBRARY_DETAIL';
export const DIGITAL_LIBRARY_ADD_EDIT_START = 'DIGITAL_LIBRARY_ADD_EDIT_START';
export const DIGITAL_LIBRARY_ADD_EDIT_SUCCESS = 'DIGITAL_LIBRARY_ADD_EDIT_SUCCESS';
export const DIGITAL_LIBRARY_ADD_EDIT_FAIL = 'DIGITAL_LIBRARY_ADD_EDIT_FAIL';
export const DIGITAL_LIBRARY_DELETE = 'DIGITAL_LIBRARY_DELETE';

export const GROUP_LIST_START = 'GROUP_LIST_START';
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS';
export const GROUP_LIST_FAIL = 'GROUP_LIST_FAIL';
export const GROUP_LIST_FILTER = 'GROUP_LIST_FILTER';
export const GROUP_DETAIL = 'GROUP_DETAIL';
export const GROUP_ADD_EDIT_START = 'GROUP_ADD_EDIT_START';
export const GROUP_ADD_EDIT_SUCCESS = 'GROUP_ADD_EDIT_SUCCESS';
export const GROUP_ADD_EDIT_FAIL = 'GROUP_ADD_EDIT_FAIL';
export const GROUP_DELETE = 'GROUP_DELETE';


// export const ROLE_ADD_EDIT_START = 'ROLE_ADD_EDIT_START';
// export const ROLE_ADD_EDIT_SUCCESS = 'ROLE_ADD_EDIT_SUCCESS';
export const ROLE_ADD_EDIT_SUCCESS_MESSAGE = 'ROLE_ADD_EDIT_SUCCESS_MESSAGE';
// export const ROLE_ADD_EDIT_FAIL = 'ROLE_ADD_EDIT_FAIL';
export const ROLE_DETAIL_START = 'ROLE_DETAIL_START';
export const ROLE_DETAIL_FAIL = 'ROLE_DETAIL_FAIL';
// export const ROLE_DETAIL = 'ROLE_DETAIL';

export const CONTACT_LIST_START = 'CONTACT_LIST_START';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';
export const CONTACT_DETAIL = 'CONTACT_DETAIL';
export const CONTACT_ADD_EDIT_START = 'CONTACT_ADD_EDIT_START';
export const CONTACT_ADD_EDIT_SUCCESS = 'CONTACT_ADD_EDIT_SUCCESS';
export const CONTACT_ADD_EDIT_FAIL = 'CONTACT_ADD_EDIT_FAIL';
export const CONTACT_DELETE = 'CONTACT_DELETE';


export const REPLAY_LIST_START = 'REPLAY_LIST_START';
export const REPLAY_LIST_SUCCESS = 'REPLAY_LIST_SUCCESS';
export const REPLAY_LIST_FAIL = 'REPLAY_LIST_FAIL';
export const REPLAY_LIST_FILTER = 'REPLAY_LIST_FILTER';
export const REPLAY_DETAIL = 'REPLAY_DETAIL';
export const REPLAY_ADD_EDIT_START = 'REPLAY_ADD_EDIT_START';
export const REPLAY_ADD_EDIT_SUCCESS = 'REPLAY_ADD_EDIT_SUCCESS';
export const REPLAY_ADD_EDIT_FAIL = 'REPLAY_ADD_EDIT_FAIL';
export const REPLAY_DELETE = 'REPLAY_DELETE';

export const DATASET_META_LIST_START = 'DATASET_META_LIST_START';
export const DATASET_META_LIST_SUCCESS = 'DATASET_META_LIST_SUCCESS';
export const DATASET_META_LIST_FAIL = 'DATASET_META_LIST_FAIL';
export const DATASET_META_LIST_FILTER = 'DATASET_META_LIST_FILTER';
export const DATASET_META_DETAIL = 'DATASET_META_DETAIL';
export const DATASET_META_ADD_EDIT_START = 'DATASET_META_ADD_EDIT_START';
export const DATASET_META_ADD_EDIT_SUCCESS = 'DATASET_META_ADD_EDIT_SUCCESS';
export const DATASET_META_ADD_EDIT_FAIL = 'DATASET_META_ADD_EDIT_FAIL';
export const DATASET_META_DELETE = 'DATASET_META_DELETE';


export const USER_REQUEST_LIST_START = 'USER_REQUEST_LIST_START';
export const USER_REQUEST_LIST_SUCCESS = 'USER_REQUEST_LIST_SUCCESS';
export const USER_REQUEST_LIST_FAIL = 'USER_REQUEST_LIST_FAIL';
export const USER_REQUEST_LIST_FILTER = 'USER_REQUEST_LIST_FILTER';
export const USER_REQUEST_STATUS_UPDATE = 'USER_REQUEST_STATUS_UPDATE';
export const USER_REQUEST_UPDATE_START = 'USER_REQUEST_UPDATE_START';
export const USER_REQUEST_UPDATE_FAIL = 'USER_REQUEST_UPDATE_FAIL';
export const USER_REQUEST_DETAIL = 'USER_REQUEST_DETAIL';